#!/bin/bash

# =============================================================================
# QUICK FIX FOR RENDER EMAIL ISSUE
# =============================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🔍 DIAGNOSIS: Why emails don't work on Render"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "❌ PROBLEM:"
echo "   MailHog only works locally (localhost:1025)"
echo "   Render server can't access 'localhost' - it needs a real email service"
echo ""
echo "✅ SOLUTION:"
echo "   Configure Render to use Mailgun instead of MailHog"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 STEP-BY-STEP FIX:"
echo ""
echo "STEP 1: Configure Render Environment Variables"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Option A - Use the script (Automated):"
echo "  1. Get your Render API key:"
echo "     https://dashboard.render.com/u/settings/api-keys"
echo ""
echo "  2. Set it:"
echo "     export RENDER_API_KEY='your-key-here'"
echo ""
echo "  3. Run the script:"
echo "     bash configure-render-mailgun.sh"
echo ""
echo "Option B - Manual (via Render Dashboard):"
echo "  1. Go to: https://dashboard.render.com/web/srv-cu83f7ij1k6c73c81nv0"
echo "  2. Click 'Environment' tab"
echo "  3. Add/Update these variables:"
echo ""
echo "     EMAIL_PROVIDER = mailgun"
echo "     MAILGUN_API_KEY = 384194fbcc249187502fb33969b35269-96164d60-b4388e96"
echo "     MAILGUN_DOMAIN = sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
echo "     EMAIL_FROM = noreply@sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
echo "     SMTP_HOST = smtp.mailgun.org"
echo "     SMTP_PORT = 587"
echo "     SMTP_USER = postmaster@sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
echo "     SMTP_PASS = 9e1d5b8936fc15ec09e88b08908e2a37-5e1ffd43-becdfdc6"
echo ""
echo "  4. Click 'Save Changes'"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "STEP 2: Authorize Your Email in Mailgun"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "⚠️  CRITICAL: Mailgun sandbox only sends to authorized emails!"
echo ""
echo "  1. Open Mailgun Dashboard:"
echo "     https://app.mailgun.com/app/sending/domains/sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
echo ""
echo "  2. Find 'Authorized Recipients' section"
echo ""
echo "  3. Click 'Add Recipient'"
echo ""
echo "  4. Enter YOUR email address (the one you'll test with)"
echo ""
echo "  5. Mailgun sends you a verification email"
echo ""
echo "  6. Open that email and click the verification link"
echo ""
echo "  7. You're now authorized! ✅"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "STEP 3: Redeploy on Render"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "  1. Go to: https://dashboard.render.com/web/srv-cu83f7ij1k6c73c81nv0"
echo "  2. Click 'Manual Deploy' button"
echo "  3. Select 'Deploy latest commit'"
echo "  4. Wait for deployment to complete (~2-3 minutes)"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "STEP 4: Test!"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "  Register with your AUTHORIZED email and check your inbox!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
read -p "Do you want to see the manual Render configuration now? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "Opening Render dashboard in browser..."
    echo ""
    
    if command -v open &> /dev/null; then
        open "https://dashboard.render.com/web/srv-cu83f7ij1k6c73c81nv0/env"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "https://dashboard.render.com/web/srv-cu83f7ij1k6c73c81nv0/env"
    else
        echo "Please open this URL manually:"
        echo "https://dashboard.render.com/web/srv-cu83f7ij1k6c73c81nv0/env"
    fi
    
    echo ""
    echo "Also opening Mailgun dashboard..."
    
    if command -v open &> /dev/null; then
        open "https://app.mailgun.com/app/sending/domains/sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "https://app.mailgun.com/app/sending/domains/sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
    else
        echo "Please open this URL manually:"
        echo "https://app.mailgun.com/app/sending/domains/sandboxcd6106b9f4d54da78846462008c1678b.mailgun.org"
    fi
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  💡 SUMMARY"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Local (MailHog):    ✅ Working - emails at http://localhost:8025"
echo "Render (Mailgun):   ⚠️  Needs configuration (follow steps above)"
echo ""
echo "After completing all steps:"
echo "  • Render will use Mailgun for real email delivery"
echo "  • Local dev still uses MailHog (no changes needed)"
echo "  • You can receive real emails on your authorized address"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
