/**
 * Calendar Service
 * Phase 4.2: Generate .ics calendar files for events
 *
 * Features:
 * - Create .ics calendar invitations
 * - Support for Google Calendar, Apple Calendar, Outlook
 * - Automatic timezone handling
 * - RSVP tracking via calendar
 * - Event reminders
 */

import ical from 'ical-generator';
import loggingService from './loggingService.js';

class CalendarService {
  /**
   * Generate .ics file content for an event
   *
   * @param {Object} event - Event details
   * @param {Object} invitation - Invitation details
   * @returns {string} - .ics file content
   */
  generateEventCalendar(event, invitation = null) {
    try {
      // Create calendar
      const calendar = ical({
        prodId: {
          company: 'SecureGate',
          product: 'Event Management',
          language: 'EN'
        },
        name: event.name,
        timezone: process.env.TIMEZONE || 'Africa/Nairobi',
        ttl: 3600, // 1 hour refresh interval
      });

      // Prepare event details
      const eventData = {
        start: new Date(event.start_date),
        end: new Date(event.end_date),
        summary: event.name,
        description: this.formatEventDescription(event, invitation),
        location: event.location || 'TBA',
        url: invitation
          ? `${process.env.CLIENT_ORIGIN}/event/${event.id}/details?code=${invitation.event_qr_code}`
          : `${process.env.CLIENT_ORIGIN}/event/${event.id}/details`,
        organizer: {
          name: 'SecureGate Event Management',
          email: process.env.MAILGUN_FROM_EMAIL || 'events@securegate.com'
        },
        status: 'CONFIRMED',
        busyStatus: 'BUSY',
        sequence: 0,
        transparency: 'OPAQUE',
      };

      // Add attendee if invitation provided
      if (invitation && invitation.visitor_email) {
        eventData.attendees = [{
          email: invitation.visitor_email,
          name: invitation.visitor_name || invitation.visitor_email,
          rsvp: true,
          status: this.mapRSVPStatusToCalendar(invitation.rsvp_status),
          type: 'INDIVIDUAL'
        }];
      }

      // Add alarms/reminders
      eventData.alarms = [
        {
          type: 'display',
          trigger: 86400, // 24 hours before (in seconds)
          description: `Reminder: ${event.name} tomorrow`
        },
        {
          type: 'display',
          trigger: 3600, // 1 hour before
          description: `Reminder: ${event.name} in 1 hour`
        }
      ];

      // Add event to calendar
      calendar.createEvent(eventData);

      // Return .ics content
      return calendar.toString();
    } catch (error) {
      loggingService.logError('Failed to generate event calendar', error);
      throw error;
    }
  }

  /**
   * Format event description for calendar
   */
  formatEventDescription(event, invitation) {
    let description = event.description || '';

    // Add event details
    if (event.dress_code) {
      description += `\n\nDress Code: ${event.dress_code}`;
    }

    if (event.parking_instructions) {
      description += `\n\nParking: ${event.parking_instructions}`;
    }

    if (event.special_instructions) {
      description += `\n\nSpecial Instructions: ${event.special_instructions}`;
    }

    // Add personal invitation details
    if (invitation) {
      if (invitation.event_qr_code) {
        description += `\n\nYour Event Pass: ${invitation.event_qr_code}`;
      }

      if (invitation.plus_one_count > 0) {
        description += `\n\nYou may bring ${invitation.plus_one_count} guest(s)`;
      }

      if (invitation.custom_message) {
        description += `\n\nPersonal Message: ${invitation.custom_message}`;
      }
    }

    description += '\n\n---\nGenerated by SecureGate Event Management';

    return description;
  }

  /**
   * Map RSVP status to calendar status
   */
  mapRSVPStatusToCalendar(rsvpStatus) {
    const statusMap = {
      'attending': 'ACCEPTED',
      'not_attending': 'DECLINED',
      'maybe': 'TENTATIVE',
      'pending': 'NEEDS-ACTION'
    };

    return statusMap[rsvpStatus] || 'NEEDS-ACTION';
  }

  /**
   * Generate calendar file for multiple events (feed)
   */
  generateEventsFeed(events) {
    try {
      const calendar = ical({
        prodId: {
          company: 'SecureGate',
          product: 'Event Management',
          language: 'EN'
        },
        name: 'SecureGate Events',
        timezone: process.env.TIMEZONE || 'Africa/Nairobi',
        ttl: 3600,
        method: 'PUBLISH'
      });

      events.forEach(event => {
        calendar.createEvent({
          start: new Date(event.start_date),
          end: new Date(event.end_date),
          summary: event.name,
          description: event.description || '',
          location: event.location || 'TBA',
          url: `${process.env.CLIENT_ORIGIN}/event/${event.id}/details`,
          organizer: {
            name: 'SecureGate Event Management',
            email: process.env.MAILGUN_FROM_EMAIL || 'events@securegate.com'
          },
          status: event.status === 'published' || event.status === 'ongoing' ? 'CONFIRMED' : 'TENTATIVE'
        });
      });

      return calendar.toString();
    } catch (error) {
      loggingService.logError('Failed to generate events feed', error);
      throw error;
    }
  }

  /**
   * Generate calendar update/cancellation
   */
  generateEventUpdate(event, invitation, action = 'UPDATE') {
    try {
      const calendar = ical({
        prodId: {
          company: 'SecureGate',
          product: 'Event Management',
          language: 'EN'
        },
        method: action === 'CANCEL' ? 'CANCEL' : 'REQUEST',
        name: event.name,
        timezone: process.env.TIMEZONE || 'Africa/Nairobi',
      });

      const eventData = {
        start: new Date(event.start_date),
        end: new Date(event.end_date),
        summary: event.name,
        description: this.formatEventDescription(event, invitation),
        location: event.location || 'TBA',
        url: `${process.env.CLIENT_ORIGIN}/event/${event.id}/details`,
        organizer: {
          name: 'SecureGate Event Management',
          email: process.env.MAILGUN_FROM_EMAIL || 'events@securegate.com'
        },
        status: action === 'CANCEL' ? 'CANCELLED' : 'CONFIRMED',
        sequence: 1, // Increment for updates
      };

      if (invitation && invitation.visitor_email) {
        eventData.attendees = [{
          email: invitation.visitor_email,
          name: invitation.visitor_name || invitation.visitor_email,
          rsvp: true,
          status: this.mapRSVPStatusToCalendar(invitation.rsvp_status)
        }];
      }

      calendar.createEvent(eventData);

      return calendar.toString();
    } catch (error) {
      loggingService.logError('Failed to generate event update', error);
      throw error;
    }
  }

  /**
   * Get calendar file as Buffer for email attachment
   */
  getCalendarAttachment(event, invitation) {
    try {
      const icsContent = this.generateEventCalendar(event, invitation);
      return {
        filename: `${event.name.replace(/[^a-z0-9]/gi, '_')}.ics`,
        content: Buffer.from(icsContent, 'utf-8'),
        contentType: 'text/calendar; charset=utf-8; method=REQUEST'
      };
    } catch (error) {
      loggingService.logError('Failed to create calendar attachment', error);
      throw error;
    }
  }

  /**
   * Generate "Add to Calendar" links for web
   */
  generateCalendarLinks(event, invitation = null) {
    const baseUrl = invitation
      ? `${process.env.CLIENT_ORIGIN}/event/${event.id}/details?code=${invitation.event_qr_code}`
      : `${process.env.CLIENT_ORIGIN}/event/${event.id}/details`;

    const startDate = new Date(event.start_date);
    const endDate = new Date(event.end_date);

    // Format dates for Google Calendar (YYYYMMDDTHHmmssZ)
    const formatGoogleDate = (date) => {
      return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    const googleStart = formatGoogleDate(startDate);
    const googleEnd = formatGoogleDate(endDate);

    const description = encodeURIComponent(
      this.formatEventDescription(event, invitation)
    );

    const location = encodeURIComponent(event.location || '');
    const title = encodeURIComponent(event.name);

    return {
      google: `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${googleStart}/${googleEnd}&details=${description}&location=${location}&sf=true&output=xml`,

      outlook: `https://outlook.live.com/calendar/0/deeplink/compose?subject=${title}&startdt=${startDate.toISOString()}&enddt=${endDate.toISOString()}&body=${description}&location=${location}&path=/calendar/action/compose&rru=addevent`,

      office365: `https://outlook.office.com/calendar/0/deeplink/compose?subject=${title}&startdt=${startDate.toISOString()}&enddt=${endDate.toISOString()}&body=${description}&location=${location}&path=/calendar/action/compose&rru=addevent`,

      yahoo: `https://calendar.yahoo.com/?v=60&view=d&type=20&title=${title}&st=${formatGoogleDate(startDate)}&et=${formatGoogleDate(endDate)}&desc=${description}&in_loc=${location}`,

      // .ics download endpoint
      ics: `${process.env.API_URL || 'http://localhost:3001'}/api/events/${event.id}/calendar${invitation ? `?code=${invitation.event_qr_code}` : ''}`
    };
  }
}

export default new CalendarService();
